### ISSUE TITLE
Spell/Grammar error in readme

### ISSUE THREAD

**Issue by rootanand** [Ruban-P/Master-Mind#8]
Game Init Screen Design.
System generates a random 4 color secret code.
Your goal is to crack the secret code.
Display the result after each attempt.
If you guess the correct code within 12 attempts, you are the WINNER, otherwise you will LOSE. 
Score will be based on the number of attempts. (lower the better)

**Comment by Ruban-P** [comment]
Thank you sir. i have done it.
